# Generated by Django 5.2.14 on 2026-05-11 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del país')),
                ('code_iso', models.CharField(max_length=2, unique=True, verbose_name='Código ISO')),
                ('continent', models.CharField(max_length=100, verbose_name='Continente')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre del producto')),
                ('category', models.CharField(max_length=100, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad vendida')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor total')),
                ('sale_date', models.DateField(verbose_name='Fecha de venta')),
                ('growth_percentage', models.FloatField(verbose_name='Porcentaje de crecimiento')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='logistics.country', verbose_name='País')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='logistics.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date'],
            },
        ),
    ]
