# Generated by Django 5.2.14 on 2026-05-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='growth_percentage',
        ),
    ]
