# Generated by Django 5.2.14 on 2026-05-16 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_sale_growth_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del punto de venta')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_points', to='logistics.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Punto de venta',
                'verbose_name_plural': 'Puntos de venta',
                'ordering': ['country__name', 'city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='logistics.salespoint', verbose_name='Punto de venta'),
        ),
    ]
